-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.

CREATE TABLE Usuario (
ID_USUARIO INTEGER PRIMARY KEY,
SENHA VARCHAR(),
SN_ATIVO INTEGER
)

CREATE TABLE Eventos (
TP_EVENTO VARCHAR(),
DH_EVENTO VARCHAR(),
ID_USUARIO INTEGER,
ID_PACIENTE INTEGER
)

CREATE TABLE Paciente (
ID_PACIENTE INTEGER PRIMARY KEY,
CPF VARCHAR(),
NOME VARCHAR(),
SOBRENOME VARCHAR(),
DT_NASCIMENTO DATETIME,
EMAIL VARCHAR(),
TELEFONE VARCHAR(),
ENDERECO VARCHAR(),
PROFISSAO VARCHAR(),
ID_USUARIO INTEGER
)

CREATE TABLE Vacinação (
ID_VACINA INTEGER,
ID_COLABORADOR INTEGER,
ID_PACIENTE INTEGER,
DH_VACINACAO VARCHAR(),
QUANTIDADE BIGINT()
)

CREATE TABLE Vacina (
ID_VACINA INTEGER PRIMARY KEY,
NOME VARCHAR(),
QTD_PADRAO VARCHAR(),
SN_ATIVO INTEGER
)

CREATE TABLE Colaborador (
ID_COLABORADOR INTEGER PRIMARY KEY,
TP_COLABORADOR VARCHAR(),
CPF VARCHAR(),
NOME VARCHAR(),
SOBRENOME VARCHAR(),
EMAIL VARCHAR(),
TELEFONE VARCHAR(),
ID_USUARIO INTEGER
)

